### ISSUE TITLE
Infografia Jeanette Arlet Salazar Nicolas

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Arlet04#1]
[ASSEMBLY SCRIPT.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Arlet04/files/15204651/ASSEMBLY.SCRIPT.pdf)

**Comment by carlos0716c** [comment]
CALIFICADO DE ACUERDO A LA RÚBRICA

Partes de la infografía: 4
Coherencia y pertinencia: 4
Organización de la información: 4
Diseño y composición de la infografía: 4
Creatividad: 4
Total=4
CALIFICACIÓN=20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
